### ISSUE TITLE
react or ts ?

### ISSUE THREAD

**Issue by gbw1120** [qiuziz/react-image-map#10]
![image](https://user-images.githubusercontent.com/35133102/105930388-8c41bc80-6084-11eb-91d1-029d05083ac4.png)

**Comment by qiuziz** [comment]
react and ts :D

**Comment by gbw1120** [comment]
May I use ECMAScript 6 to use this component?
![image](https://user-images.githubusercontent.com/35133102/105931911-05421380-6087-11eb-89db-5c23cd5ef8e4.png)

**Comment by qiuziz** [comment]
Yes, remove ts code

like this

```
import {ImageMap} from '@qiuz/react-image-map';

...

const onMapClick = (area, index) => {
	const tip = `click map${area.href || index + 1}`;
	console.log(tip);
	alert(tip);
}

```

**Comment by gbw1120** [comment]
need this
![image](https://user-images.githubusercontent.com/35133102/105939819-e34f8d80-6094-11eb-8c54-41dbc3da4dbd.png)

different
![image](https://user-images.githubusercontent.com/35133102/105939846-f5313080-6094-11eb-8610-1136dfe2eec4.png)
import {ImageMap} from '@qiuz/react-image-map';

...

const onMapClick = (area, index) => {
	const tip = `click map${area.href || index + 1}`;
	console.log(tip);
	alert(tip);
}

**Comment by qiuziz** [comment]
I don't get it. 

Can you describe it clearly？

**Comment by gbw1120** [comment]
I want  function of Taylor case 
http://blog.qiuz.site/widget/react-image-map/?imgSrc=img_address

**Comment by qiuziz** [comment]
The `imgSrc` is img url

![image](https://user-images.githubusercontent.com/13669987/105941123-af299c00-6097-11eb-8bbf-fa9eec1c6e41.png)

And the real link is  http://blog.qiuz.site/widget/react-image-map/?imgSrc=http://5b0988e595225.cdn.sohucs.com/images/20170920/2a178d11bc8b4178a387398b5658e105.jpeg
