### ISSUE TITLE
onLoad fires before the image appears

### ISSUE THREAD

**Issue by mattdimicelli** [qiuziz/react-image-map#27]
Hello,
I am using react-image-map to render a very large image map (about 4500 x 6500px).  On my slow computer, it takes a few seconds to load (maybe four seconds?), during which time it's space is a white box.  I want to implement a loading indicator, but I've noticed that the onLoad event from <ImageMap> is firing while the box is still white, seconds before the image actually appears.

Do you have any idea how I can listen for the moment when the image actually renders to the screen?

Thank you.

**Comment by qiuziz** [comment]
Sorry I’ve been busy with my work.

Can you give me this image for test?

**Comment by mattdimicelli** [comment]
Hi qiuziz.  Thank you for getting back to me and now I'm sorry about my delayed response; I was traveling.

Believe it or not, I really can't share this particular image with you.  Only because it is an illustration that I paid for, and the artists' condition/contract of use was that I would not share the full resolution image.  However, I am certain that this would happen with other images as well, because I am using three of these images (from the same artist), and the same "delay" happens with all of them.

Would you maybe be able to try this with any other very large image?  For example, with a large wallpaper image found on Google?

**Comment by qiuziz** [comment]
It don't happen for https://s1.1zoom.me/big3/476/Forests_Roads_479818.jpg.

I think you can provide a minimum reproducible code.

**Comment by mattdimicelli** [comment]
Hi qiuziz, I'm emailing you a link so that it is less public.  I trust that you won't further distribute the artwork :)  .  Thank you!

**Comment by qiuziz** [comment]
> 

I think I understand your question.

`onLoad` fires after the download not appear.

My suggestion is you can use `new Image()`，in the onLoad replace `ImageMap src`

**Comment by mattdimicelli** [comment]
Hi qiuziz,

Good afternoon.  I tried to follow your instructions I haven't had success.  If I pass the image's URL to new Image() (eg. `new Image(URL)`), it will return a HTMLImageElement (`<img />`).  I hope that I understand that much so far.  

What should I replace ImageMap src with?  I can't pass the <img /> element as a value to the src attribute, right?

**Comment by qiuziz** [comment]
```js
const [imgSrc, setImgSrc] = useState('loading img url');
const img = new Image();
img.src = 'large img url';
img.onload = () => {
  setImgSrc('large img url');
}

<ImageMap src={imgSrc} />
```

Happy coding :)

**Comment by mattdimicelli** [comment]
Quiziz,

Thank you so much for patiently guiding me thru this issue!  Thanks to you I now have a functional app.  Now I understand that since the `<ImageMap>` element is not the same thing as an `<img>` element, I shouldn't have assumed that the onLoad event would be fired by the `<ImageMap>` in the same way or conditions that it is by an `<img>`.
