### ISSUE TITLE
Global CSS cannot be imported from within node_modules

### ISSUE THREAD

**Issue by adventurini** [qiuziz/react-image-map#36]
This issue comes with NextJS build. More info found here: https://nextjs.org/docs/messages/css-npm. 

Any help would be appreciated. Thank you!

**Comment by qiuziz** [comment]
I need change webpack config, or use styled-components.

But I've been busy lately, wait a moment.

**Comment by qiuziz** [comment]
@adventurini The new version(1.1.5) use inline style, you can update.
