### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by bellmcp** [qiuziz/react-image-map#39]
There is an error in the latest version (1.1.5), Kindly help resolve or suggest any possible solutions.

`ReferenceError: window is not defined`

![Screen Shot 2022-04-22 at 2 10 53 AM](https://user-images.githubusercontent.com/32966560/164535868-6b9dea5c-1da0-4894-a4ee-87141467987f.png)

Thank you in advance.

**Comment by qiuziz** [comment]
thx for your using it, the issue is fixed in latest version
