### ISSUE TITLE
onmouseover 

### ISSUE THREAD

**Issue by frankbracq** [qiuziz/react-image-map#8]
Hi,

Is there a way to handle onmouser event with the component?

Thanks for your reply

Frank

**Comment by qiuziz** [comment]
Hi，I'm late and what do you want?

only props accept events?

**Comment by ghost** [comment]
I don't know what @frankbracq is looking for, but for me a onMapOver (similar to onMapClick) would be awesome. I would like to show a dedicated tooltip for each area.

Thanks for this awesome lib!

**Comment by qiuziz** [comment]
This advice comes from @frankbracq . Latest version(1.0.15) is access all React.Img attr and events.

Thanks for @frankbracq advice and thanks for your use @oprobst-ethz .

**Comment by ghost** [comment]
Thanks for the quick reply. Do you have the source code for your sample site (http://blog.qiuz.site/q/react-image-map/) available? I see that you use map onMouseOver and it would be very helpful to see how I can achieve this as well.

Thanks

**Comment by qiuziz** [comment]
The ImageMap component is accept React.Img all props.

The source code at this repo https://github.com/qiuziz/react-image-map/blob/master/src/container/images-map/index.tsx#L30

**Comment by ghost** [comment]
Thank you so much!
