### ISSUE TITLE
Alt attribute For the Image

### ISSUE THREAD

**Issue by portatlas** [qiuziz/react-image-map#9]
Hello, thanks for creating this image map library!

Could we add an alt attribute to the image being mapped? I have a PR but will need to be added as a collaborator to push this up.
<img width="530" alt="Screen Shot 2021-01-26 at 5 41 50 PM" src="https://user-images.githubusercontent.com/14946902/105835012-cf0c8180-5ffd-11eb-836d-fadeb7253dd5.png">

**Comment by qiuziz** [comment]
you can fork this project and create pull request

[How to Contribute to an Open Source Project on GitHub](https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github)

I guess this is helpful to you. And I'm glad this project can be useful to you.
.

**Comment by qiuziz** [comment]
Hi, the 1.0.15 version is access all React.img attr. and events，you can use `yarn add -D @qiuz/react-image-map@latest` to upgrade.

thanks for you advise and thanks for you use the lib.
